name: CI-CD

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t ai-service .

      - name: Push to ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin $ECR
          docker tag ai-service:latest $ECR/ai-service:latest
          docker push $ECR/ai-service:latest

      - name: Deploy to EKS
        run: kubectl apply -f k8s/
      